version: '3'
services:
  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    volumes:
      - '/Users/vandana/Documents/mongodata:/data/db'
    ports:
      - '27018:27018'
  node-app:
    image: node-app
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    depends_on:
      - mongo
